blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/13MrBlackCat13/Sudoku/discussions
    about: Please ask and answer questions here.
  - name: Security Vulnerabilities
    url: https://github.com/13MrBlackCat13/Sudoku/security/policy
    about: Please report security vulnerabilities here.